### ISSUE TITLE
Server crash when Beacon was placed

### ISSUE THREAD

**Issue by dandin87** [Communi-Suggestu/Saecularia-Caudices#1]
Beacon was placed down and then the server crashed. Crashed every time the chunk was loaded. 
Yarn Mapped Crash Report - https://aofpaste.com/utoqigofoc.yaml
Mixin transformation of com.communi.suggestu.saecularia.caudices.fabric.mixin.platform.world.level.block.entity.IBeaconBlockEntityAccessor failed
Illegal classload request for accessor mixin com.communi.suggestu.saecularia.caudices.fabric.mixin.platform.world.level.block.entity.IBeaconBlockEntityAccessor. The mixin is missing from saeculariacaudices.mixins.json which owns package com.communi.suggestu.saecularia.caudices.fabric.mixin.* and the mixin has not been applied

**Comment by dandin87** [comment]
![2022-12-19_19 35 25](https://user-images.githubusercontent.com/9329117/208579899-530e933f-ec08-42a1-af24-4804fab0da89.png)
Beacon was also underwater. Other beacons on the server seem to be fine. Not sure why only this one was causing this issue

**Comment by dandin87** [comment]
![image](https://user-images.githubusercontent.com/9329117/208580701-f55ebd2a-a12c-4997-ba53-57467cbaa676.png)
Update, it appears water is indeed the reason it is crashing.
A little water is fine, but if the water is too high above it, then it causes the crash
beacons placed with water at block level 10-11 crash

**Comment by Linguardium** [comment]
seems the accessor needed is missing from the mixins file https://github.com/Communi-Suggestu/Saecularia-Caudices/blob/79a5bfdcf2a9eb8de267b52eca6243c37ca431c9/fabric/src/main/resources/saeculariacaudices.mixins.json#L20

**Comment by Noobidoo** [comment]
This looks like it's fixed in a6299af67db948a4488748a445fb2123905b096c

**Comment by marchermans** [comment]
Yes this was indeed fixed
